# Generated by Django 5.0.7 on 2024-08-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "Блог", "verbose_name_plural": "Блоги"},
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="description",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="name",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="views",
        ),
        migrations.AddField(
            model_name="blog",
            name="count_views",
            field=models.IntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Количество просмотров",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="products/photo",
                verbose_name="Изображение",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="is_publication",
            field=models.BooleanField(default=False, verbose_name="Создать?"),
        ),
        migrations.AddField(
            model_name="blog",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Введите заголовок",
                max_length=50,
                null=True,
                verbose_name="Заголовок",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Идентификатор"
            ),
        ),
    ]
