# Generated by Django 5.0.7 on 2024-08-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Добавьте изображение",
                null=True,
                upload_to="media",
                verbose_name="Изображение (превью)",
            ),
        ),
    ]
