# Generated by Django 5.0.7 on 2024-08-29 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_preview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Введите номер версии продукта",
                        null=True,
                        verbose_name="Номер версии продукта",
                    ),
                ),
                (
                    "version_name",
                    models.CharField(
                        blank=True,
                        help_text="Введите наименование версии продукта",
                        max_length=50,
                        null=True,
                        verbose_name="Наименование версии продукта",
                    ),
                ),
                (
                    "version_sign",
                    models.BooleanField(
                        default=True,
                        help_text="Версия активна?",
                        verbose_name="признак текущей версии",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="version",
                        to="catalog.product",
                        verbose_name="Наименование продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
                "ordering": ["product", "version_number", "version_name"],
            },
        ),
    ]
