# Generated by Django 5.0.7 on 2024-09-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Статус публикации продукта",
                verbose_name="Опубликовано",
            ),
        ),
    ]
