# Generated by Django 5.0.7 on 2024-09-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name"],
                "permissions": (
                    ("can_unpublish_product", "Отменить публикацию"),
                    ("can_change_product_description", "Изменить описание"),
                    ("can_change_product_category", "Изменить категорию"),
                ),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
